---
# Configure zabbix-server
- name: Place zabbix-server config
  become: yes
  template:
    src: zabbix-server.conf
    dest: /etc/zabbix/zabbix_server.conf
    backup: yes
  register: server

- name: Place java-gateway config
  become: yes
  template:
    src: zabbix-java-gateway.conf
    dest: /etc/zabbix/zabbix_java_gateway.conf
    backup: yes
  register: java

- name: Place apache config
  become: yes
  template:
    src: apache.conf
    dest: /etc/zabbix/apache.conf
    backup: yes
  register: apache

- name: Place frontend
  become: yes
  template:
    src: frontend.php
    dest: /etc/zabbix/web/zabbix.conf.php
    backup: yes
