---
#tasks to install
#we will install zabbix 5.0 latest with postgresql and timescale db.

- name: create folder to place state files of what is done
  become: yes
  file:
    path: /iw
    state: directory


- name: Add an apt key for zabbix
  become: yes
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present

- name: Add an apt key for postgresql
  become: yes
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"
    state: present 

- name: Add apt repo for zabbix
  become: yes
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/5.0/ubuntu focal main"
    state: present

- name: Add apt repo for postgresql
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
    state: present

- name: Add ppa for timescaledb
  become: yes
  apt_repository:
    repo: ppa:timescale/timescaledb-ppa

- name: install packages
  become: yes
  apt:
    name: ['libpq-dev','python3-psycopg2','zabbix-server-pgsql','zabbix-frontend-php','php7.4-pgsql','zabbix-apache-conf','zabbix-agent','timescaledb-postgresql-12']

- name: place setup script
  become: yes
  copy:
    src: runonce.sh
    dest: /iw/runonce.sh
    owner: root
    group: root
    mode: '0700'

- name: run setupscript
  become: yes
  command: "/iw/runonce.sh creates=/iw/setup"
