---
#tasks to install
#we will install zabbix 5.0 latest with postgresql and timescale db.
- name: Add an apt key for zabbix
  become: yes
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present

- name: Add an apt key for postgresql
  become: yes
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"
    state: present 

- name: Add apt repo for zabbix
  become: yes
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/5.0/ubuntu focal main"
    state: present

- name: Add apt repo for postgresql
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
    state: present

- name: Add ppa for timescaledb
  - apt_repository:
    repo: ppa:timescale/timescaledb-ppa

- name: install packages
  become: yes
  apt:
    name: ['zabbix-server-pgsql','zabbix-frontend-php','php7.4-pgsql','zabbix-apache-conf','zabbix-agent','timescaledb-postgresql-12']

- name: register timscaledb settings
  become: yes
  command: "timescaledb-tune --quiet --yes"

- name: Create a new database with name "zabbix"
  become: yes
  postgresql_db:
    name: zabbix

- name: Create zabbix user on postgresql
  become: yes
  postgresql_user:
    db: zabbix
    name: zabbix
    password: ceec4eif7ya

- name: import zabbix database
  become: yes
  command: "zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix"

- name: add extension for timescaledb
  become: yes
  command: "echo "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;" | sudo -u postgres psql zabbix"

- name: run zabbix timescaledb settings
  become: yes
  command: "cat /usr/share/doc/zabbix-server-pgsql*/timescaledb.sql | sudo -u zabbix psql zabbix"

